_target_: erc.model.cross_attention.CrossAttentionRoberta
config: 
  wav: kresnik/wav2vec2-large-xlsr-korean
  txt: klue/roberta-large

criterions:
  cls:
    _target_: erc.optims.FocalLoss
  reg:
    _target_: torch.nn.MSELoss
cls_coef: 0.7