_target_: erc.model.mlp_mixer.MLP_Mixer_Roberta
config: 
  wav: kresnik/wav2vec2-large-xlsr-korean
  txt: klue/roberta-large
  mlp_mixer: 
    # image_size: [ 1024, 768 ]
    channels: 1
    patch_size: 16
    dim: 512
    depth: 12
    num_classes: 9

criterions:
  cls:
    _target_: erc.optims.FocalLoss
  reg:
    _target_: torch.nn.MSELoss
cls_coef: 0.7