_target_: erc.model.simple_concat.SimpleConcat
config: 
  wav: kresnik/wav2vec2-large-xlsr-korean
  txt: klue/bert-base

criterions:
  cls:
    _target_: torch.nn.CrossEntropyLoss
  reg:
    _target_: torch.nn.MSELoss
cls_coef: 0.7