dataset:
  _target_: erc.datasets.KEMDDataset
  return_bio: False
  max_length_wav: 200_000
  max_length_txt: 50
  tokenizer_name: klue/bert-base
  validation_fold: 4
  mode: train

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 16
  dataset: ${dataset}