dataset:
  _target_: erc.datasets.KEMDy19Dataset
  base_path: ./data/KEMDy19
  generate_csv: False
  return_full_bio: False

  wav2vec_pretrain: facebook/wav2vec2-base-960h

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 16
  dataset: ${dataset}