hydra:
  job:
    chdir: False  # keep hydra = 1.1 change directory behavior
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  
defaults:
  - _self_
  - dataset: hf
  - model: mlp_mixer_roberta
  - scheduler: cosine_warmup

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  num_workers: 4
  dataset: ${dataset}

optim:
  _target_: torch.optim.AdamW
  eps: 1e-8
  lr: 1e-5
  weight_decay: 1e-6

misc:
  seed: 42
  debug: False
  modes: [ train, valid ]

module:
  _target_: erc.trainer.ERCModule
  _recursive_: False
  separate_lr: 
    wav_model: 1e-5
    txt_model: 1e-5
    mlp_mixer: 1e-4
  load_from_checkpoint:
  
logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: RobertaL Final
  entity: etri-erc
  name: RobertaL

# https://pytorch-lightning.readthedocs.io/en/stable/common/trainer.html
trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 30
  devices: 1
  accelerator: gpu
  gradient_clip_val: 1
  log_every_n_steps: 100
  # DEBUGGING FLAGS. TODO: Split
  # limit_train_batches: 0.001
  # limit_val_batches: 0.01

callbacks:
  # https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.ModelCheckpoint.html
  checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: ${hydra:run.dir}
    filename: "{step}-valid_acc{epoch/valid_acc:.3f}"
    monitor: "epoch/valid_acc"
    mode: max
    save_top_k: 1
    save_last: False
    # Is useful to set it to False when metric names contain / as this will result in extra folders
    # auto_insert_metric_name: False

  # https://pytorch-lightning.readthedocs.io/en/stable/common/early_stopping.html
  early_stop:
    _target_: pytorch_lightning.callbacks.early_stopping.EarlyStopping
    monitor: epoch/valid_acc
    mode: max
    patience: 5
  
  # https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.LearningRateMonitor.html
  lr_monitor:
    _target_: pytorch_lightning.callbacks.LearningRateMonitor
    logging_interval: step
    log_momentum: False