hydra:
  job:
    chdir: False  # keep hydra = 1.1 change directory behavior
  
defaults:
  - dataset: hf
  - model: classify

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  num_workers: 4
  dataset: ${dataset}

optim:
  _target_: torch.optim.AdamW
  eps: 1e-8
  lr: 1e-5
  weight_decay: 1e-6

misc:
  seed: 42
  debug: False
  # "w11wo/wav2vec2-xls-r-300m-korean" for other pre-trained

module:
  _target_: erc.trainer.ERCModule
  move_metrics_to_cpu: ${trainer.move_metrics_to_cpu}

logger:
  _target_: pytorch_lightning.loggers.WandbLogger
  project: etri-erc
  entity: etri-erc
  name: ERC-wav

trainer:
  _target_: pytorch_lightning.Trainer
  max_epochs: 200
  devices: 1
  accelerator: gpu
  gradient_clip_val: 1
  move_metrics_to_cpu: False
  limit_train_batches: 0.5
  # limit_val_batches: 0.01
  # log_every_n_steps: 2