_target_: erc.datasets.HF_KEMD
paths: [ kemdy19, kemdy20 ]
validation_fold: 4
wav_processor: kresnik/wav2vec2-large-xlsr-korean
sampling_rate: 16_000
wav_max_length: 112_000 # 16_000 * 7, 7secs duration
txt_processor: klue/bert-base
txt_max_length: 64
load_from_cache_file: True
num_proc: 8