dataset:
  _target_: erc.datasets.KEMDDataset
  return_bio: False
  # max_length_wav / 16_000 = duration(sec)
  max_length_wav: 80_000
  max_length_txt: 50
  tokenizer_name: klue/bert-base
  validation_fold: 4
  num_data: False # To Debug 