_target_: erc.datasets.KEMDDataset
return_bio: False
# max_length_wav / 16_000 = duration(sec)
max_length_wav: None
max_length_txt: None
tokenizer_name: None
validation_fold: 4
num_data: False # To Debug 